### ISSUE TITLE
Cava refuses to compile on Arch

### ISSUE THREAD

**Issue by arithefirst** [karlstav/cava#595] opened 2024-11-04 23:39 UTC
**Describe the bug**

Cava will not compile on arch linux. (AUR cava and cava-git as well as building from source)

**To Reproduce**

1. Be on arch linux
2. attempt to build cava
3. throws the following errors and refuses to build

```
configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
/usr/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
/usr/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
configure.ac:306: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: autom4te failed with exit status: 1
configure.ac:7: warning: The macro 'AC_PROG_CC_STDC' is obsolete.
configure.ac:7: You should run autoupdate.
./lib/autoconf/c.m4:1669: AC_PROG_CC_STDC is expanded from...
configure.ac:7: the top level
configure.ac:2: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:4: error: possibly undefined macro: AM_PROG_AR
configure.ac:9: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.ac:40: error: possibly undefined macro: AM_CONDITIONAL
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:12: installing './config.guess'
configure.ac:12: installing './config.sub'
Makefile.am:13: error: OSX does not appear in AM_CONDITIONAL
Makefile.am:22: error: FREEBSD does not appear in AM_CONDITIONAL
Makefile.am:23: error: CAVAFONT does not appear in AM_CONDITIONAL
Makefile.am:32: error: ALSA does not appear in AM_CONDITIONAL
Makefile.am:36: error: PORTAUDIO does not appear in AM_CONDITIONAL
Makefile.am:40: error: PIPEWIRE does not appear in AM_CONDITIONAL
Makefile.am:44: error: PULSE does not appear in AM_CONDITIONAL
Makefile.am:48: error: SNDIO does not appear in AM_CONDITIONAL
Makefile.am:52: error: OSS does not appear in AM_CONDITIONAL
Makefile.am:56: error: JACK does not appear in AM_CONDITIONAL
Makefile.am:60: error: NCURSES does not appear in AM_CONDITIONAL
Makefile.am:64: error: SDL does not appear in AM_CONDITIONAL
Makefile.am:68: error: SDL_GLSL does not appear in AM_CONDITIONAL
Makefile.am:6: warning: source file 'input/common.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least one source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However, this
automake: behavior may change in a future Automake major version, with object
automake: files being placed in the same subdirectory as the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibility.
Makefile.am:6: warning: source file 'input/fifo.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'input/shmem.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'output/terminal_noncurses.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'output/raw.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'output/noritake.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:33: warning: source file 'input/alsa.c' is in a subdirectory,
Makefile.am:33: but option 'subdir-objects' is disabled
Makefile.am:37: warning: source file 'input/portaudio.c' is in a subdirectory,
Makefile.am:37: but option 'subdir-objects' is disabled
Makefile.am:41: warning: source file 'input/pipewire.c' is in a subdirectory,
Makefile.am:41: but option 'subdir-objects' is disabled
Makefile.am:45: warning: source file 'input/pulse.c' is in a subdirectory,
Makefile.am:45: but option 'subdir-objects' is disabled
Makefile.am:49: warning: source file 'input/sndio.c' is in a subdirectory,
Makefile.am:49: but option 'subdir-objects' is disabled
Makefile.am:53: warning: source file 'input/oss.c' is in a subdirectory,
Makefile.am:53: but option 'subdir-objects' is disabled
Makefile.am:57: warning: source file 'input/jack.c' is in a subdirectory,
Makefile.am:57: but option 'subdir-objects' is disabled
Makefile.am:61: warning: source file 'output/terminal_ncurses.c' is in a subdirectory,
Makefile.am:61: but option 'subdir-objects' is disabled
Makefile.am:65: warning: source file 'output/sdl_cava.c' is in a subdirectory,
Makefile.am:65: but option 'subdir-objects' is disabled
Makefile.am:69: warning: source file 'output/sdl_glsl.c' is in a subdirectory,
Makefile.am:69: but option 'subdir-objects' is disabled
Makefile.am: installing './depcomp'
/usr/share/automake-1.17/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.17/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.17/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.17/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.17/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.17/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
```

**Expected behavior**

Cava properly and successfully compiles and runs

**Desktop (please complete the following information):**

 - OS: Arch Linux 
 - Version: Linux 6.6.59-1-lts

**Terminal emulator**
- Ghostty
- 0.1.0-main+e26847cc

**Comment by karlstav** [comment] 2024-11-08 18:24
Duplicate of #594

**Closed** 2024-11-08 18:24 UTC

**Comment by manzup3r** [comment] 2024-11-10 15:56
for anyone facing this issue on arch linux, here's how to bypass the autoconfig error:

1.    install the downgrade tool from AUR with `pacaur -S downgrade` or `yay -S downgrade`, if u don't already have it installed.
2.    use it to downgrade autoconfig and autoconfig-archive by running `sudo downgrade autoconfig` and `sudo downgrade autoconfig-archive`.
3.    select older versions from each list, and then u should be good to install cava. u'll get a confirmation message if the downgrade succeeded or failed. proceed to last step once u've successfully downgraded both.
4.    finally, run `pacaur -S cava`—it should install as usual. 

as u can probably surmise, this isn’t a cava bug, as discussed in the author's link above, it's autconfig's m4 code, and as far as i know, this is the easiest workaround
