### ISSUE TITLE
Compile failure on Gentoo

### ISSUE THREAD

**Issue by ajakk** [karlstav/cava#236] opened 2018-09-17 16:14 UTC
GCC gives this error when compiling:

    In file included from cava.c:69:
    config.c: In function ‘load_config’:
    config.c:411:2: error: too many arguments to function ‘iniparser_getseckeys’
      iniparser_getseckeys(ini, "eq", keys);`

Removing the "keys" argument from the mentioned function allows a complete compilation.

**Comment by karlstav** [comment] 2018-09-17 19:02
Gentoo uses an older version of iniparser, you can resolve this by using the following configure option

```
./configure  --enable-legacy_iniparser
```

**Comment by saeidscorp** [comment] 2019-12-06 13:59
There are already instructions for dealing with old `iniparser` in README, which is nice, but maybe some hint in the readme relating the `--enable-legacy_iniparser` to Gentoo would be nicer; as there a couple of issues related to this, but all closed and not looked in when first searching (`is:open`). I was about to fall for this and file a new issue myself :)

**Comment by karlstav** [comment] 2019-12-07 11:52
there is also #83 #97 and #186 so making a better fix for this is probably a good idea. 

4 years ago i [wrote](https://github.com/karlstav/cava/issues/83#issuecomment-167613429) that it was difficult, but I could just  use [AC_LINK_IFELSE](https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Running-the-Linker.html) to test whether `iniparser_getseckeys` runs ok with two or three arguments.

**Comment by karlstav** [comment] 2019-12-08 20:58
@saeidscorp can you test the commit in the new branch?

you must run the whole:
```
./autogen.sh
./configure
make
```
again, without the `--enable-legacy_iniparser` flag.

**Comment by saeidscorp** [comment] 2019-12-08 23:38
Yes, that did it. Thanks.

However, I ran into another (unrelated) issue first, where make refuses to build after the initial build, saying:

`[saeid:~/Apps/cava] autolegacyiniparserfix* ± make
make[1]: Entering directory '/home/saeid/Apps/cava'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/saeid/Apps/cava'`

And I had to clone the whole repo from scratch (or touch a source file). Shouldn't there be a mechanism for `make` (or `autogen`) to recognize the non-present output binaries to trigger a rebuild? Or am I missing something obvious here?

**Comment by karlstav** [comment] 2019-12-09 07:32
That's great!

Are you saying that you get "nothing to do" even with no binaries preset? I don't think that should happen. You can always remove the binaries with 'make clean' then make should work as normal.

**Comment by saeidscorp** [comment] 2019-12-09 09:38
Yes. Although `make clean` works as intended, `git clean -fd` and then `./autogen.sh` and `./configure` followed by `make` does nothing.

**Comment by karlstav** [comment] 2019-12-09 19:50
that is probably because the cava binary is listed in .gitignore so it's not deleted by `git clean`.

**Comment by saeidscorp** [comment] 2019-12-09 20:12
Yes that was it. How could I miss that!

**Comment by karlstav** [comment] 2019-12-09 20:49
Don't know if that's common or not. Didn't really know it was even there, it was added by someone else years back. This did however prompt me to do some cleaning in there, now I can finaly do `git status` and get `working tree clean`, thanks!

**Closed by karlstav** 2019-12-09 20:49 UTC
