### ISSUE TITLE
Output to serial

### ISSUE THREAD

**Issue by Lokagan** [karlstav/cava#100] opened 2016-05-07 20:54 UTC
I'd like to use CAVA to send FFT result over serial line in order to process them in an arduino driving WS2812 led strip... Can you provide a serial output instead of terminal in order to do something like that ?

**Comment by karlstav** [comment] 2016-05-08 21:38
@Lokagan I actually had planned to make something like this myself one day.

It would be pretty easy to make somekind of serial/file/fifo output. Do you have any preferences on the data format of the output?

**Comment by CelestialWalrus** [comment] 2016-05-09 19:00
Possibly related to #24?

**Comment by karlstav** [comment] 2016-05-09 19:12
@CelestialWalrus indeed, I'll make a separate branch to start working on it. How about raw 16bit ouput with each value representing the height of a bar, number of bars can be specified in the config with some static value as default (100?). Output whould also be specified in the config, with perhaps stdout as default.

**Comment by CelestialWalrus** [comment] 2016-05-13 19:24
@karlstav sounds good. There should also be a way to define the maximum height.

**Comment by karlstav** [comment] 2016-05-21 11:20
I have something working in the raw output branch now. 

from new config example:
```
# raw is a 16 bit data stream of the bar heights that can be used to send to other applications
# raw defaults to 200 bars, can be adjusted in the bars option above
; method = ncurses

# raw output target defaults to stdout, a fifo will be created if target does not exist
; raw_target = /dev/stdout
```
so set the `method = raw` and `raw_target` to whatever you might need.

so @Lokagan if you are using an rpi I guess you would want raw_traget to be  `/dev/ttyAMA0`, you might need to run cava as root, which will probably lead you in to other problems....

as for @mikaelbrun in #101 just make up some raw_target and cava will create a fifo with that name in the cava dir and ouptut the values there. 

I'm trying to think of a way to test the actual output, it might not even be correct as of now.

**Comment by Lokagan** [comment] 2016-07-05 22:16
Hmm I think a start word is required to sync rpi & duino serial.

**Comment by karlstav** [comment] 2016-07-06 20:22
could you elaborate? 

would it be sufficient to output some given character when cava starts?

**Comment by Lokagan** [comment] 2016-07-09 18:28
It'll not be suffisient. Each packet should be like :
Datastart,col1_value,col2_value,...
In ascii format, with a unique start word and a unique data separator in order to sync process between duino and rpi. As parameters it will be suffisient to have : col max value, number of bars, stereo/mono mode. Personnally i need 2x6 bars in scale 0-255 :)

**Comment by davea** [comment] 2016-07-21 14:11
I've got this working nicely on a Raspberry PI driving a 8x8 grid of WS2812 LEDs to form a simple 8-band visualiser, so just wanted to say thanks for the `raw-output` branch!

One question: Either I'm reading the bytes incorrectly, or every other value seems to be 0 - is this correct?

**Comment by karlstav** [comment] 2016-07-30 11:35
@davea the raw output format is 16 bit so if you are reading it byte by byte, that might be the cause of every other value seemingly becoming 0. 

I think it still needs some tuning, also i might make it configurable (binary 8/16-bit bit or ascii with a custom max value). Number of bars and  stereo/mono is still configurable in other parts of the config file.

**Comment by karlstav** [comment] 2016-08-24 19:37
@Lokagan and others who may be interested, I added some more stuff like ascii mode and delimiters. From config file:

```
# raw output target defaults to stdout, a fifo will be created if target does not exist
; raw_target = /dev/stdout

# raw data format, can be binary or ascii
; data_format = binary

# binary bit format, can be '8bit' (0-255) or '16bit' (0-65530) 
; bit_format = 16bit

# ascii max value, in ascii mode range will run from 0 to value specified here
; ascii_max_range = 1000

# ascii delimiters, in ascii format each bar and frame is seperated by a delimiters.
# use decimal value in ascii table (i.e. 59 = ';' and 10 = '\n' (line feed)) 
; bar_delimiter = 59
; frame_delimiter = 10
```

Let me know if it's usable, I think I'll merge this soon, but it can always be modified or improved later.

**Comment by karlstav** [comment] 2016-11-17 17:37
we have the raw output mode now, so I'll close this

**Closed by karlstav** 2016-11-17 17:37 UTC
