### ISSUE TITLE
cava 9.x does not react with sensitivity = 0

### ISSUE THREAD

**Issue by zpamaral** [karlstav/cava#521] opened 2023-08-30 12:19 UTC
**When/where was the bug introduced?**
cava 0.9.x (cava 0.8.x works fine).

**Describe the bug**
cava 0.9.x compiles fine, but when it runs the bars do not animate. The bar graph just sits there showing the frequencies and a minimum line.

**To Reproduce**
1. Compile cava 0.8.x and cava 0.9.x
2. run either one with the same config file and Background Music 0.4.0
3. cava 0.8.x will work as expected, whereas 0.9.x will not
4. See error on image attached.

**Expected behavior**
See a sound representation as a frequency bar graph.

**Screenshots**
Attached below.
![cava 0 8 3](https://github.com/karlstav/cava/assets/36271736/71132d3e-828c-4bbe-b5d8-abfea0eb2862)
cava 0.9.1
![cava 0 9 1](https://github.com/karlstav/cava/assets/36271736/f69aab52-9729-43cf-b20e-af4fe96fdc0d)
cava 0.8.3

**Desktop**
 - OS: macOS 10.11.6 (El Capitan)
 - Version: 10.11.6

**Terminal emulator**
- Terminal.app (iTerm shows the same problem)
- 2.6.1

**Additional context**
I will be delighted to elaborate on additional pertinent information if requested. Thank you.

**Comment by karlstav** [comment] 2023-08-30 18:19
can't reproduce, there might have been an issue in cava 0.9.0 but it should be fixed now.

what is the output of cava -v

**Comment by zpamaral** [comment] 2023-08-30 18:43
Hello,
Thank you for the prompt reply.

The output for the cava version that works well is cava 0.8.3 and the output for the one that does not work is cava 0.9.1. However, I tested for the whole 0.8.x series and all versions work, and tested both 0.9.x versions and they do not work.

On a different computer running macOS 12.6.8, the cava 0.9.1 runs without issues.

On both computers and for all the mentioned versions of cava, compiling is never an issue (even with OpenGL support).

Thank you.

> No dia 30/08/2023, às 19:19, karl ***@***.***> escreveu:
> 
> 
> can't reproduce, there might have been an issue in cava 0.9.0 but it should be fixed now.
> 
> what is the output of cava -v
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

ZP
--
José Pedro Sousa do Amaral

Boy, n.:
        A noise with dirt on it.

**Comment by karlstav** [comment] 2023-08-30 19:38
does it work to capture audio from the mic? just set source to auto

**Comment by zpamaral** [comment] 2023-08-30 21:46
Hello,
When the source is set to auto, cava 0.8.3 works as expected (I can talk and watch the sonogram) but cava 0.9.1 does not.

Thank you.

> No dia 30/08/2023, às 20:38, karl ***@***.***> escreveu:
> 
> does it work to capture audio from the mic? just set source to auto

ZP
--
José Pedro Sousa do Amaral

If marriage is outlawed, only outlaws will have inlaws.

**Comment by karlstav** [comment] 2023-08-31 05:15
Good, that rules out background music at least. Is "method" set explicitly to portaudio in both cases? (Just try to remove the ; before that config option)

**Comment by zpamaral** [comment] 2023-08-31 09:58
Yes, it is. The semicolons were removed thus:

method = portaudio
source = "Background Music"

and for the mic test I did:

method = portaudio
source = auto

Thank you.

ZP

**Comment by karlstav** [comment] 2023-08-31 10:49
are you able to test before and after this commit:

https://github.com/karlstav/cava/commit/4400d5b94b2c7877f5d56951a2a90e818e4bf309

**Comment by zpamaral** [comment] 2023-08-31 11:42
Hello,
Yes.

cava-6c10d7acfe works as expected.
cava-4400d5b94b works as expected.
cava-a014284bb8 works as expected.
cava-2d212b5079 works as expected.
cava-bc16184527 works as expected.
cava-23325a1d54 works as expected.
cava-0d77307606 works as expected.<- Last commit that works!
cava-af0c6d8c69 compiles but does not work.
cava-8ef51b7be9 compiles but does not work.
cava-4b4e16a094 compiles but does not work.
cava-5669d3256e compiles but does not work.
cava-522063d192 compiles but does not work.

> No dia 31/08/2023, às 11:49, karl ***@***.***> escreveu:
> 
> are you able to test before and after this commit:
> 
> 4400d5b

ZP
--
José Pedro Sousa do Amaral

Ser poeta é ser mais alto, é ser maior
Do que os homens! Morder como quem beija!
É ser mendigo e dar como quem seja
Rei do Reino de Aquém e de Além Dor!

F. Espanca

**Comment by karlstav** [comment] 2023-08-31 11:49
it's this commit: 

https://github.com/karlstav/cava/commit/af0c6d8c697bde3d7b026ab3bfad6da65c5dc491

so it's something about the sensitivity that breaks it.

do you have any settings there? can you just dump your entire config here?

**Comment by zpamaral** [comment] 2023-08-31 11:54
Hello,
Yes, I have sensitivity = 0 .

Here it goes:


## Configuration file for CAVA.
# Remove the ; to change parameters.


[general]

# Smoothing mode. Can be 'normal', 'scientific' or 'waves'. DEPRECATED as of 0.6.0
; mode = normal

# Accepts only non-negative values.
; framerate = 60

# 'autosens' will attempt to decrease sensitivity if the bars peak. 1 = on, 0 = off
# new as of 0.6.0 autosens of low values (dynamic range)
# 'overshoot' allows bars to overshoot (in % of terminal height) without initiating autosens. DEPRECATED as of 0.6.0
autosens = 1
; overshoot = 0

# Manual sensitivity in %. If autosens is enabled, this will only be the initial value.
# 200 means double height. Accepts only non-negative values.
sensitivity = 0

# The number of bars (0-512). 0 sets it to auto (fill up console).
# Bars' width and space between bars in number of characters.
; bars = 0
; bar_width = 2
; bar_spacing = 1
# bar_height is only used for output in "noritake" format
; bar_height = 32

# For SDL width and space between bars is in pixels, defaults are:
; bar_width = 20
; bar_spacing = 5

# sdl_glsl have these default values, they are only used to calulate max number of bars.
; bar_width = 1
; bar_spacing = 0


# Lower and higher cutoff frequencies for lowest and highest bars
# the bandwidth of the visualizer.
# Note: there is a minimum total bandwidth of 43Mhz x number of bars.
# Cava will automatically increase the higher cutoff if a too low band is specified.
lower_cutoff_freq = 50
higher_cutoff_freq = 10000


# Seconds with no input before cava goes to sleep mode. Cava will not perform FFT or drawing and
# only check for input once per second. Cava will wake up once input is detected. 0 = disable.
; sleep_timer = 0


[input]

# Audio capturing method. Possible methods are: 'pulse', 'alsa', 'fifo', 'sndio' or 'shmem'
# Defaults to 'pulse', 'pipewire', 'alsa' or 'fifo', in that order, dependent on what support cava was built with.
# On windows this is automatic and no input settings are needed.
#
# All input methods uses the same config variable 'source'
# to define where it should get the audio.
#
# For pulseaudio and pipewire 'source' will be the source. Default: 'auto', which uses the monitor source of the default sink
# (all pulseaudio sinks(outputs) have 'monitor' sources(inputs) associated with them).
#
# For piepwire 'source' will be the object name or object.serial of the device to capture from.
# Both input and output devices are supported.
#
# For alsa 'source' will be the capture device.
# For fifo 'source' will be the path to fifo-file.
# For shmem 'source' will be /squeezelite-AA:BB:CC:DD:EE:FF where 'AA:BB:CC:DD:EE:FF' will be squeezelite's MAC address
; method = pulse
; source = auto

; method = pipewire
; source = auto

; method = alsa
; source = hw:Loopback,1

; method = fifo
; source = /tmp/mpd.fifo
; sample_rate = 44100
; sample_bits = 16

; method = shmem
; source = /squeezelite-AA:BB:CC:DD:EE:FF

; method = portaudio
; source = auto

; method = portaudio
; source = "Soundflower (2ch)"

; method = portaudio
; source = "Dispositivo combinado"

method = portaudio
source = "Background Music"

[output]

# Output method. Can be 'ncurses', 'noncurses', 'raw', 'noritake', 'sdl'
# or 'sdl_glsl'.
# 'noncurses' uses a custom framebuffer technique and prints only changes
# from frame to frame in the terminal. 'ncurses' is default if supported.
#
# 'raw' is an 8 or 16 bit (configurable via the 'bit_format' option) data
# stream of the bar heights that can be used to send to other applications.
# 'raw' defaults to 200 bars, which can be adjusted in the 'bars' option above.
#
# 'noritake' outputs a bitmap in the format expected by a Noritake VFD display
#  in graphic mode. It only support the 3000 series graphical VFDs for now.
#
# 'sdl' uses the Simple DirectMedia Layer to render in a graphical context.
# 'sdl_glsl' uses SDL to create an OpenGL context. Write your own shaders or
# use one of the predefined ones.
method = ncurses
; method = noncurses
; method = raw
; method = sdl_glsl

# Orientation of the visualization. Can be 'bottom', 'top', 'left' or 'right'.
# Default is 'bottom'. Other orientations are only supported on sdl and ncurses
# output. Note: many fonts have weird glyphs for 'top' and 'right' characters,
# which can make ncurses not look right.
orientation = bottom

# Visual channels. Can be 'stereo' or 'mono'.
# 'stereo' mirrors both channels with low frequencies in center.
# 'mono' outputs left to right lowest to highest frequencies.
# 'mono_option' set mono to either take input from 'left', 'right' or 'average'.
# set 'reverse' to 1 to display frequencies the other way around.
channels = stereo
; mono_option = average
; reverse = 0

# Raw output target. A fifo will be created if target does not exist.
; raw_target = /dev/stdout

# Raw data format. Can be 'binary' or 'ascii'.
; data_format = binary

# Binary bit format, can be '8bit' (0-255) or '16bit' (0-65530).
; bit_format = 16bit

# Ascii max value. In 'ascii' mode range will run from 0 to value specified here
; ascii_max_range = 1000

# Ascii delimiters. In ascii format each bar and frame is separated by a delimiters.
# Use decimal value in ascii table (i.e. 59 = ';' and 10 = '\n' (line feed)).
; bar_delimiter = 59
; frame_delimiter = 10

# sdl window size and position. -1,-1 is centered.
; sdl_width = 500
; sdl_height = 250
; sdl_x = -1
; sdl_y= -1

# set label on bars on the x-axis. Can be 'frequency' or 'none'. Default: 'none'
# 'frequency' displays the lower cut off frequency of the bar above.
# Only supported on ncurses and noncurses output.
xaxis = frequency

# enable alacritty synchronized updates. 1 = on, 0 = off
# removes flickering in alacritty terminal emulator.
# defaults to off since the behaviour in other terminal emulators is unknown
; alacritty_sync = 0

# Shaders for sdl_glsl, located in $HOME/.config/cava/shaders
; vertex_shader = pass_through.vert
; fragment_shader = bar_spectrum.frag

; for glsl output mode, keep rendering even if no audio
; continuous_rendering = 0

[color]

# Colors can be one of seven predefined: black, blue, cyan, green, magenta, red, white, yellow.
# Or defined by hex code '#xxxxxx' (hex code must be within ''). User defined colors requires
# a terminal that can change color definitions such as Gnome-terminal or rxvt.
# default is to keep current terminal color
; background = default
; foreground = default

# SDL and sdl_glsl only support hex code colors, these are the default:
; background = '#111111'
; foreground = '#33ffff'


# Gradient mode, only hex defined colors are supported,
# background must also be defined in hex or remain commented out. 1 = on, 0 = off.
# You can define as many as 8 different colors. They range from bottom to top of screen
; gradient = 0
; gradient_count = 8
; gradient_color_1 = '#59cc33'
; gradient_color_2 = '#80cc33'
; gradient_color_3 = '#a6cc33'
; gradient_color_4 = '#cccc33'
; gradient_color_5 = '#cca633'
; gradient_color_6 = '#cc8033'
; gradient_color_7 = '#cc5933'
; gradient_color_8 = '#cc3333'



[smoothing]

# Percentage value for integral smoothing. Takes values from 0 - 100.
# Higher values means smoother, but less precise. 0 to disable.
# DEPRECATED as of 0.8.0, use noise_reduction instead
; integral = 77

# Disables or enables the so-called "Monstercat smoothing" with or without "waves". Set to 0 to disable.
; monstercat = 0
; waves = 0

# Set gravity percentage for "drop off". Higher values means bars will drop faster.
# Accepts only non-negative values. 50 means half gravity, 200 means double. Set to 0 to disable "drop off".
# DEPRECATED as of 0.8.0, use noise_reduction instead
; gravity = 200


# In bar height, bars that would have been lower that this will not be drawn.
# DEPRECATED as of 0.8.0
; ignore = 0

# Noise reduction, int 0 - 100. default 77
# the raw visualization is very noisy, this factor adjusts the integral and gravity filters to keep the signal smooth
# 100 will be very slow and smooth, 0 will be fast but noisy.
noise_reduction = 0


[eq]

# This one is tricky. You can have as much keys as you want.
# Remember to uncomment more than one key! More keys = more precision.
# Look at readme.md on github for further explanations and examples.
1 = 2 # bass
2 = 2
3 = 2 # midtone
4 = 2
5 = 2 # treble


->ends here

> No dia 31/08/2023, às 12:49, karl ***@***.***> escreveu:
> 
> 
> it's this commit:
> 
> af0c6d8
> 
> so it's something about the sensitivity that breaks it.
> 
> do you have any settings there? can you just dump your entire config here?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

ZP
--
José Pedro Sousa do Amaral

Work is the curse of the drinking class.
        -- Oscar Wilde

**Comment by karlstav** [comment] 2023-08-31 12:07
great to hear it worked out!

i should probably make a guard against setting `sensitivity = 0` does not really make any sense. Just accidentally worked before.

**Closed** 2023-09-07 18:02 UTC
