### ISSUE TITLE
After closing cava, terminal colors are changed.

### ISSUE THREAD

**Issue by aeikenberry** [karlstav/cava#132] opened 2017-02-08 18:07 UTC
After i press Q and exit cava, all my terminal colors are much brighter and look wrong. I'm using urxvt, colors are set in Xresources. Any idea how to avoid that? Right now i just close the terminal window after using cava if i'm done with it.

**Comment by karlstav** [comment] 2017-02-11 09:27
@aeikenberry I'm not able to reproduce, could I get your config file for cava and your Xresoures file?

**Comment by chelovechishko** [comment] 2017-02-17 07:59
I use gnome-terminal-3.22 and not default colors. After closing cava green and red become brighter (my default colors much darker). For example, with this check in terminal before cava and after: `echo -e "start \033[0;31m test_1 \033[0m \033[0;36m test_2  \033[0m \033[0;32m test_3  \033[0m end"`

I don't think that config somehow affect this. By default colors are commented. Even if i use some hex color which differs from cyan there is same result.

As for me, the problem in [this](https://github.com/karlstav/cava/commit/daed29a9c54287eecde507f56e947e55b204cf1c) commit, but without it a get black on black (instead of green on black).

cava-0.4.2 had not this issue.

**Comment by karlstav** [comment] 2017-02-17 08:33
ok, I think I know why now.

In order for hex-colors to work, cava redefines the color definition for red and green:

line 57 in terminal_ncurses.c:

```
	if (col.col == -2) {
		init_color(1, (int)(col.R * magic), (int)(col.G * magic), (int)(col.B * magic));
	}
	if (bgcol.col == -2) {
		init_color(2, (int)(bgcol.R * magic), (int)(bgcol.G * magic), (int)(bgcol.B * magic));
	}

```

I have not found a way to store the previous definition in order to revert back to them when cava exits, so i simply set them back to default values:


line 147:


```
	init_color(1, 1000, 0, 0);
	init_color(2, 0, 1000, 0);
```

not optimal I know! When looking at the function [color_content](https://linux.die.net/man/3/color_content), this actually looks solvable.

**Comment by chelovechishko** [comment] 2017-02-17 12:51
According to [this](https://cboard.cprogramming.com/linux-programming/150031-ncurses-restore-color-endwin.html) **standend()** is good enough. For me colors returned to previous state.

**Closed** 2017-02-25 12:02 UTC
