### ISSUE TITLE
ST terminal has issues displaying

### ISSUE THREAD

**Issue by UltimaQuazar** [karlstav/cava#175] opened 2017-09-04 02:59 UTC
Cava doesn't seem to run fluidly on the suckless [st](st.suckless.org) terminal.
The visualizer tears and seems to lag a bit in comparison to running it on URxvt which runs it smoothly.

**Comment by Bfgeshka** [comment] 2017-09-04 04:54
Cannot reproduce, using pretty recent st version from master, cava works fine here.

**Comment by karlstav** [comment] 2017-09-09 17:04
Works fine here as well using 0.4.1, not as smooth as URxvt, but smoother than Gnome terminal. 

I get the issue with the horizontal lines, but I think that's just because of the font.

**Comment by anko** [comment] 2017-09-10 15:10
How is this a cava issue? Do other similar applications run better on `st`?

**Comment by karlstav** [comment] 2017-10-29 16:58
@UltimaQuazar I'm closing this for now, if you have some more info on this issue just reopen it.

**Closed by karlstav** 2017-10-29 16:58 UTC
