### ISSUE TITLE
glitches in alacritty terminal

### ISSUE THREAD

**Issue by crozbo** [karlstav/cava#356] opened 2020-05-27 07:58 UTC
I have glitches when i use cava in alacritty. 
![cava-bug](https://user-images.githubusercontent.com/35157367/82993058-4d90c980-a000-11ea-8c20-75e9c41217d4.png)
In KDE konsole there is no that glitch, so I don't know it is alacritty or cava bug.

**Comment by karlstav** [comment] 2020-05-27 18:23
I am 90% sure that this is an issue with the font. 

https://unicode.org/charts/PDF/U2580.pdf

the lower partial block characters looks slightly wider then the full block character. 

Can you try to change the font?

**Comment by freijon** [comment] 2020-05-27 19:03
I'm having the same issue. I tried `Inconsolata` and `Ubuntu Mono`. I guess your assumption is correct, because changing the font makes a difference. With `Inconsolata` the lower part is actually wider than the top. This is on Gentoo. However, on Arch and using the exact same fonts, I don't have this issue...?

**Comment by karlstav** [comment] 2020-05-27 19:49
gentoo might be using an older version:

https://packages.gentoo.org/packages/media-fonts/inconsolata

https://www.archlinux.org/packages/community/any/ttf-inconsolata/

looks to be in constant development:

https://github.com/googlefonts/Inconsolata

**Comment by crozbo** [comment] 2020-05-28 05:52
Yes the problem is with font, there a different glitches when I change font. But that is only in Alacritty, so probably Alacritty font rendering cause this.
Do I need to report this Alaciritty devs?

**Comment by freijon** [comment] 2020-05-28 13:26
On Gentoo I upgraded alacritty from 0.4.0 to 0.4.2 and the visual glitches are gone... What version are you using @crozbo?

**Comment by crozbo** [comment] 2020-05-28 14:30
I use archlinux, alacirtty 0.4.2

**Comment by curlpipe** [comment] 2020-05-28 23:52
Works completely fine on my Arch Linux system using Alacritty (0.4.2 and 0.5.0-dev) with "DejaVu Sans Mono for Powerline" as my font.

**Comment by crozbo** [comment] 2020-05-29 17:15
@curlpipe the glitches are with some fonts, for example Ubuntu Mono. Can you try with different fonts.

**Comment by curlpipe** [comment] 2020-05-30 13:06
![image](https://user-images.githubusercontent.com/11898833/83328956-9f468780-a27e-11ea-966b-ad6002a2ed27.png)


Even when I have Ubuntu Mono as my font on alacritty 0.4.2, there are no issues.

**Comment by karlstav** [comment] 2020-05-30 13:30
Are you using same version and config? ncurses / noncurses. From 0.7.0 noncurses is default. noncurses is just normal printf instead of using ncurses.

-
Karl

**Comment by curlpipe** [comment] 2020-05-30 13:47
I was using ncurses but even with noncurses, both ubuntu mono and dejavu

![image](https://user-images.githubusercontent.com/11898833/83329952-25190180-a284-11ea-82ba-6c0996211ace.png)

Works perfectly fine.

I can't seem to reproduce this strange font issue, no matter what combination of settings I use. Perhaps its something to do with the actual font files that @crozbo has?

(I'm using Cava 0.6.1)

**Comment by crozbo** [comment] 2020-06-02 19:16
@karlstav I use default config. I tested with ncurses and noncurses and the problem is still exists.
@curlpipe I have lastest ubuntu fonts instaled from arch(ttf-ubuntu-font-family 0.83-5) and that is one of fonts have glitches.
I don't know is this bug because something is wrong with my system. For now i use Inconsolata font and everything work, so it is not that critical bug.

**Comment by karlstav** [comment] 2020-06-05 17:50
locale settings?

**Comment by sistematico** [comment] 2021-06-14 20:44
Sorry for necro-posting and cross-posting, but, same issue here, Arch Linux, Alacritty, cava(from AUR), Ubuntu Mono(and many others), LANG=pt_BR.UTF-8

Updated system.

![image](https://user-images.githubusercontent.com/97509/121956748-7ed55800-cd2f-11eb-9c55-a101619620bf.png)

**Comment by SoyBison** [comment] 2021-07-13 00:04
I am also having this issue. Arch Linux, QTile WM, Alacritty, cava-git from AUR, locale set to en_US.UTF-8, brand new install. Using Adobe source code pro fonts, but it also happens in liberation Mono, doesn't happen with the same fonts in kitty.

**Comment by karlstav** [comment] 2021-07-19 12:02
I will be closing this as the later comments has nothing to do with the original issue (as far as I can see). Both the issue with the top bar offset and with the horizontal lines are related to alacritty and not cava

**Closed by karlstav** 2021-07-19 12:02 UTC
