### ISSUE TITLE
A2DP bluetooth PulseAudio support

### ISSUE THREAD

**Issue by pasimko** [karlstav/cava#126] opened 2017-01-06 03:27 UTC
Currently, CAVA cannot detect the A2DP or HSP/HFP sinks on my bluetooth headphones. I am using PulseAudio, but previously with ALSA it didn't work either. Am I missing something, or is this not yet possible?

**Comment by karlstav** [comment] 2017-01-06 08:48
duplicate of your own issue from two weeks ago #122??

**Closed by karlstav** 2017-01-06 08:48 UTC
