### ISSUE TITLE
Blank Screen but when selecting you can see it working

### ISSUE THREAD

**Issue by WooxHimself** [karlstav/cava#444] opened 2022-04-02 19:22 UTC
**Describe the bug**

**To Reproduce**
1. Download Cava
2. Run cava command
3. Play Something
4. Select something in terminal with mouse

**Expected behavior**
Normal cava normally visible

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Latest (as of today)

**Screenshots**
![Screenshot_20220402_212106](https://user-images.githubusercontent.com/76164598/161398051-e061d276-b066-4e7f-9a9d-83a97824b20b.png)

**Comment by karlstav** [comment] 2022-04-04 19:22
duplicate of #399

**Closed by karlstav** 2022-04-04 19:22 UTC
Labels: duplicate
