### ISSUE TITLE
Gradient color bug in Konsole

### ISSUE THREAD

**Issue by 6GVp8WcnM9TPDBrw** [karlstav/cava#233] opened 2018-08-19 15:37 UTC
I don't know why, but the color with gradient are all bugged in Konsole (work fine in "normal" mode), while in gnone-terminal everything is ok

https://i.imgur.com/yOWm66Z.png

Left = Konsole
Right = Gnome Terminal

**Comment by karlstav** [comment] 2018-08-20 09:51
this is a duplicate of #194 that i closed for some reason. I will reopen that issue and close this.

**Closed by karlstav** 2018-08-20 09:51 UTC
