### ISSUE TITLE
pipewire defaults input to mic

### ISSUE THREAD

**Issue by HVisMyLife** [karlstav/cava#451] opened 2022-05-01 22:12 UTC
**When/where was the bug introduced?**
My setup: 
- os: Arch
- wm: sway (wayland)
- audio: pipewire + pipewire-pulse
- eq: easyeffects

**Describe the bug**
Cava visualizes microphone input (easyeffects source) instead of speaker output (easyeffects sink / speaker). I can change it in pavucontrol, but doing it every time isn't ideal...
I've tried changing pulse source in config in [input], but it does not make any difference  ( number / name from "pactl list sinks" )

**To Reproduce**
Launch cava with my setup.

**Terminal emulator**
- name: Kitty
- version: latest

Thanks in advance

**Comment by HVisMyLife** [comment] 2022-05-02 11:36
I've found a temporary solution. You just have to exclude cava from input recorders in easyeffects, and it automatically chooses speaker output as input.

**Comment by karlstav** [comment] 2022-05-02 17:39
I am going to re-open this issue as this seems to be general issue that more people are struggling with.

there is also a workaround mentioned [here](https://github.com/karlstav/cava/issues/422#issuecomment-994270910) in #422 

long term I think we need to create a native pipewire input module or modify the pulseaudio module so this does not happen

**Comment by kivimango** [comment] 2022-07-15 19:16
Hello. I have the same problem, cava picks up the audio from my microphone default.

I tried the fixes mentioned on #422, but it doesn't work for me, settings sources to other than microphone the bars don't move.
I remember that im using pipewire, but pactl info reports pulseaudio.

**Comment by karlstav** [comment] 2023-04-02 08:08
I have a hard time reproducing the issue.

ubunut 22.10

pipewire
Compiled with libpipewire 0.3.58
Linked with libpipewire 0.3.58

pipewire-pulse
Compiled with libpipewire 0.3.58
Linked with libpipewire 0.3.58

wireplumber
Compiled with libwireplumber 0.4.12
Linked with libwireplumber 0.4.12

![image](https://user-images.githubusercontent.com/6968928/229340141-b6803902-b392-4574-af76-de59745886e6.png)


cava audio config is default settings. cava behaves as expected, muting mic does nothing. Also tried muting with alsamixer.


If anyone else is experience this issue, please make a test to see if your .monitor source gets muted when you mute the mic on the same card. If that is the case, then this is a bug in pipewire or wireplumber.

**Comment by karlstav** [comment] 2023-04-20 20:55
closing this as we have native pipewire support now

**Closed by karlstav** 2023-04-20 20:55 UTC
Labels: bug
